### Read Top N Rows

In [5]:
import pandas as pd
pd.options.display.max_rows = 10
## read only top 5 rows
pd.read_csv('data/real-estate-transactions.csv', nrows=5)

             street        city    zip state     ...                         sale_date  price   latitude   longitude
0      3526 HIGH ST  SACRAMENTO  95838    CA     ...      Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879
1       51 OMAHA CT  SACRAMENTO  95823    CA     ...      Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028
2    2796 BRANCH ST  SACRAMENTO  95815    CA     ...      Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     ...      Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     ...      Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

[5 rows x 12 columns]

### Read File in Chunks

In [9]:
chunker=pd.read_csv('data/real-estate-transactions.csv', chunksize=20)

for i, chunk in zip(range(3), chunker):
    display(chunk)

chunker.get_chunk(size=5)

                     street            city    zip     ...       price   latitude   longitude
0              3526 HIGH ST      SACRAMENTO  95838     ...       59222  38.631913 -121.434879
1               51 OMAHA CT      SACRAMENTO  95823     ...       68212  38.478902 -121.431028
2            2796 BRANCH ST      SACRAMENTO  95815     ...       68880  38.618305 -121.443839
3          2805 JANETTE WAY      SACRAMENTO  95815     ...       69307  38.616835 -121.439146
4           6001 MCMAHON DR      SACRAMENTO  95824     ...       81900  38.519470 -121.435768
..                      ...             ...    ...     ...         ...        ...         ...
15           7340 HAMDEN PL      SACRAMENTO  95842     ...      110700  38.700051 -121.351278
16              6715 6TH ST       RIO LINDA  95673     ...      113263  38.689591 -121.452239
17  6236 LONGFORD DR Unit 1  CITRUS HEIGHTS  95621     ...      116250  38.679776 -121.314089
18          250 PERALTA AVE      SACRAMENTO  95833     ...      120000  38.612099 -121.469095
19          113 LEEWILL AVE       RIO LINDA  95673     ...      121630  38.689999 -121.463220

[20 rows x 12 columns]

                  street             city    zip     ...       price   latitude   longitude
20    6118 STONEHAND AVE   CITRUS HEIGHTS  95621     ...      122000  38.707851 -121.320707
21     4882 BANDALIN WAY       SACRAMENTO  95823     ...      122682  38.468173 -121.444071
22       7511 OAKVALE CT  NORTH HIGHLANDS  95660     ...      123000  38.702792 -121.382210
23          9 PASTURE CT       SACRAMENTO  95834     ...      124100  38.628631 -121.488097
24    3729 BAINBRIDGE DR  NORTH HIGHLANDS  95660     ...      125000  38.701499 -121.376220
..                   ...              ...    ...     ...         ...        ...         ...
35  3920 SHINING STAR DR       SACRAMENTO  95823     ...      146250  38.487420 -121.462459
36       5031 CORVAIR ST  NORTH HIGHLANDS  95660     ...      147308  38.658246 -121.375469
37        7661 NIXOS WAY       SACRAMENTO  95823     ...      148750  38.479553 -121.463317
38       7044 CARTHY WAY       SACRAMENTO  95828     ...      149593  38.498570 -121.420925
39      2442 LARKSPUR LN       SACRAMENTO  95825     ...      150000  38.585140 -121.403736

[20 rows x 12 columns]

                          street             city    zip     ...       price   latitude   longitude
40  4800 WESTLAKE PKWY Unit 2109       SACRAMENTO  95835     ...      152000  38.658812 -121.542345
41                 2178 63RD AVE       SACRAMENTO  95822     ...      154000  38.493955 -121.489660
42                  8718 ELK WAY        ELK GROVE  95624     ...      156896  38.416530 -121.379653
43            5708 RIDGEPOINT DR         ANTELOPE  95843     ...      161250  38.720270 -121.331555
44                 7315 KOALA CT  NORTH HIGHLANDS  95660     ...      161500  38.699251 -121.371414
..                           ...              ...    ...     ...         ...        ...         ...
55            1122 WILD POPPY CT             GALT  95632     ...      178760  38.287789 -121.294715
56               4520 BOMARK WAY       SACRAMENTO  95842     ...      179580  38.665724 -121.358576
57              9012 KIEFER BLVD       SACRAMENTO  95826     ...      181000  38.547011 -121.366217
58             5332 SANDSTONE ST       CARMICHAEL  95608     ...      181872  38.662105 -121.313945
59               5993 SAWYER CIR       SACRAMENTO  95823     ...      182587  38.447300 -121.435218

[20 rows x 12 columns]

                  street        city    zip state     ...                         sale_date   price   latitude   longitude
60    4844 CLYDEBANK WAY    ANTELOPE  95843    CA     ...      Wed May 21 00:00:00 EDT 2008  182716  38.714609 -121.347887
61      306 CAMELLIA WAY        GALT  95632    CA     ...      Wed May 21 00:00:00 EDT 2008  182750  38.260443 -121.297864
62      9021 MADISON AVE  ORANGEVALE  95662    CA     ...      Wed May 21 00:00:00 EDT 2008  183200  38.664186 -121.217511
63            404 6TH ST        GALT  95632    CA     ...      Wed May 21 00:00:00 EDT 2008  188741  38.251808 -121.302493
64  8317 SUNNY CREEK WAY  SACRAMENTO  95823    CA     ...      Wed May 21 00:00:00 EDT 2008  189000  38.459041 -121.424644

[5 rows x 12 columns]